### ISSUE TITLE
Attempting to replicate your work

### ISSUE THREAD

**Issue by MetalGearBronya** [w4123/GenshinVoice#18]
Dear developer, 

I'm currently working on a modding project and I've found your work to be extremely valuable. 
Unfortunately, your update has discontinued, and without a script, we can't help in maintaining the project. 

Judging by the project you forked, it seems the "result.json" was extracted from the ExcelBinOutput and TextMap used by the GrassCutter project, where they reverse engineered the game and unpacked the in-game materials. I was able to find the scripts for the character voices in there, but not the hash value used for matching audio files. Is this the right direction that I should dig deeper, or did you get that information from elsewhere? Any hint would be much appreciated. 

Of course it would be the best that you could share the script you used, and we can help in keeping this repo updated. If there was concern in posting them publicly, we can use any private sharing method you like. 

Looking forward to your reply. 

Regards, 
Bronya

**Comment by w4123** [comment]
Hi Bronya,

It gives me great satisfaction to hear that you see value in my project. However, I have been really busy recently with schoolwork, but I will update this repo soon with the latest data.

Unfortunately, I am unable to share any scripts or codes that relate to this project, as they are mostly reverse-engineered from the game and are likely to be DMCAed. I have my own script for extracting data as the GC data is often incomplete. If you wish to replicate this, I am afraid that the only possible way is to reverse-engineer the game yourself.

I noticed you're working on an audio modding project for Genshin, which is really cool. I wish I had the time to work on something like that too. I'm excited to see what you come up with and I wish you the best of luck!

Regards,
Suhui

**Comment by w4123** [comment]
I notice that the GC Resources now is rather complete and probably you can use it directly to replicate the result. Good luck.
