### ISSUE TITLE
请问有3.6版本的json文件吗？如果没有，烦请告诉一下json文件的制作办法吧

### ISSUE THREAD

**Issue by Seminery** [w4123/GenshinVoice#27]
用3.5的json分类3.6的数据集结果发现纳西妲传说任务二的语音完全没分类出来，与此同时是NoData的语音多出了四百多条。请问作者会发布3.6版本的json文件吗？如果不方便的话，就想向大家请教一下json文件的制作方法，我自己试试看。本人对编程零基础，谢谢大家啦

**Comment by Erythrocyte3803** [comment]
我仓库有整理好的，3.1~3.7所有版本合并的，不知道有没有需要。在我的AI-Hobbyist组织里面

**Comment by Seminery** [comment]
感谢！最近忙碌没有看GitHub，刚刚才在邮箱里看到（捂脸）

红血球AE3803 ***@***.***> 于 2023年6月8日周四 23:40写道：
