### ISSUE TITLE
请问resultv**.json的hash键是如何生成的？

### ISSUE THREAD

**Issue by Asassong** [w4123/GenshinVoice#3]
我也有解这些音频的工具， 但我不知道这个json文件里的内容是怎么得到的。
比如解出的音频为1001_4.wav，它对应的key为02769d079cdd376a，请问这是怎么得到的，希望能够赐教，谢谢。

**Comment by w4123** [comment]
pck文件里面本身就有hash，你解包的工具没读出来。
具体的对应内容都是从AssetBundles中的BinOutput和ExcelBinOutput中提取出来的。

**Comment by fzyxh** [comment]
能否麻烦您说一下从AssetBundles中的BinOutput和ExcelBinOutput中提取的具体流程和工具呢？我遇到了[issue 21](https://github.com/w4123/GenshinVoice/issues/21)一样的问题，3.5.0英文语音的哈希值跟json中的对应不上，想试试能不能自己提取出一份json的键值表来。十分感谢！
